.PHONY : build view clean

build :
		@# "Not much to do here. I did this Python!"
		chmod a+rx assn4
		chmod a+rx test.script 

view :
		@\less assn4
		@\less test.script	

clean :
		@\rm CashRegister.avk42
		@\rm *.pyc
